# Generated by Django 5.1.2 on 2024-11-27 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Transfer', 'Transfer')], max_length=10)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.accountinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('transfer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transfer_time', models.DateTimeField(auto_now_add=True)),
                ('transfer_from_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_from', to='accounts.accountinfo')),
                ('transfer_to_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_to', to='accounts.accountinfo')),
            ],
        ),
    ]
